#!/bin/python3
#### Imports
from theme import *
from config import *
from progress import *
import _thread
from tkinter import *
import tkinter.font as tkFont
import codecs
import time
import sys
import random
#### GUI init
rootWindow = Tk()
rootWindow.title('gcxReader')
windowPositionX = (rootWindow.winfo_screenwidth() - width) / 2
windowPositionY = (rootWindow.winfo_screenheight() - height) / 2
rootWindow.geometry('%dx%d+%d+%d' % (width, height, windowPositionX, windowPositionY))
rootWindow.configure(bg = backGroundColor)
#### Read bookValue
if len(sys.argv) >= 2 and sys.argv[1] == '' or len(sys.argv) == 1:
    text = codecs.open(bookName, 'r').read()
else:
    bookName = sys.argv[1]
    text = codecs.open(sys.argv[1], 'r').read()
text2 = text.replace('\r', ' ').replace('\n', ' ')
#### Read last reading progress
if bookName in progressDictionary:
    lastReadingCharacters = progressDictionary[bookName]
else:
    lastReadingCharacters = 666
#### Arguments dealing
if len(sys.argv) >= 3 and sys.argv[2] != '':
    calculatePointer = int(textLength * float(sys.argv[2]))
#### Global varibles
normalFont = tkFont.Font(family = fontName, size = fontSize)
characterPointer = lastReadingCharacters
rowLimit = (height) // (fontSize * 2.55)
nowRow = 0
rowStack = []
textLength = len(text)
calculatePointer = lastReadingCharacters
maxColumn = []
maxLine = 0
pythonFile = 0
otherCodes = 0
firstLineOfPage = 0
paragraphMark = set()
colorNumber = len(theme)
foreGroundColor = theme[random.randint(0, colorNumber - 1)]
#### Last reading progressing dealing
if calculatePointer >= textLength:
    calculatePointer = 0
#### thread calculating
def calculateMaxColumn():
    global textLength
    global calculatePointer
    global maxLine
    global text
    tempLimit = (width - columnMargin * 2 - centerMargin) // 2
    while calculatePointer < textLength:
        tempLine = ''
        pixelFontLength = fontSize * 1.5
        while pixelFontLength < tempLimit and calculatePointer < textLength:
            if text[calculatePointer] == '\n' or text[calculatePointer] == '\r':
                calculatePointer += 1
                paragraphMark.add(len(maxColumn))
                break
            else:
                tempLine += text[calculatePointer]
                calculatePointer += 1
            pixelFontLength += normalFont.measure(text[calculatePointer - 1])
        maxColumn.append(calculatePointer)
        maxLine += 1
_thread.start_new_thread(calculateMaxColumn, ())
#### display
def turnPage(event):
    global rowLimit
    global pointerList
    global pointerListPointer
    global nowRow
    global text2
    global firstLineOfPage
    global foreGroundColor
    firstLineOfPage = nowRow
    rowStack.append(nowRow)
    for widget in rootWindow.winfo_children():
        widget.destroy()
    expectedRow = min(nowRow + rowLimit, maxLine)
    rowHeight = (height - 2 * rowMargin) / rowLimit / height
    originRow = nowRow
    relx = columnMargin / height
    yStart = columnMargin / width
    relheight = (height - 2 * rowMargin) / rowLimit / height
    relwidth = (width - columnMargin - centerMargin - columnMargin) / 2 / width

    while nowRow < expectedRow:
        if nowRow in paragraphMark:
            foreGroundColor = theme[random.randint(0, colorNumber - 1)]
        rely = (nowRow - originRow) *  rowHeight + rowMargin / width
        Label(rootWindow, text = text2[maxColumn[nowRow]:maxColumn[nowRow + 1]], font = normalFont, fg = foreGroundColor, bg = backGroundColor, justify = LEFT, anchor = N + W).place(relheight = relheight, relwidth = relwidth, relx = relx, rely = rely)
        nowRow += 1


    expectedRow = min(nowRow + rowLimit, maxLine)
    originRow = nowRow
    relx = (width / 2 + centerMargin / 2) / width
    while nowRow < expectedRow:
        if nowRow in paragraphMark:
            foreGroundColor = theme[random.randint(0, colorNumber - 1)]
        rely = (nowRow - originRow) *  rowHeight + rowMargin / width
        Label(rootWindow, text = text2[maxColumn[nowRow]:maxColumn[nowRow + 1]], font = normalFont, fg = foreGroundColor, bg = backGroundColor, justify = LEFT, anchor = N + W).place(relheight = relheight, relwidth = relwidth, relx = relx, rely = rely)
        nowRow += 1

        rootWindow.title('%s - %.1f' % (bookName.split('.')[0], maxColumn[nowRow - 1] / textLength * 100) + '%')

#### Events listener
def turnLeft(event):
    global characterPointer
    global pointerListPointer
    global pointerList
    global nowRow
    rowStack.pop()
    nowRow = rowStack.pop()
    turnPage(event)

#### Close with Saving
def closeWithSaving():
    global nowRow
    progressDictionary[bookName] = maxColumn[nowRow - 1]
    progressFile = open('progress.py', 'w')
    progressFile.write('progressDictionary = {\n')
    for key, value in progressDictionary.items():
        progressFile.write('\t\'%s\':%s,\n' % (key, value))
    progressFile.write('}')
    progressFile.close()
    exit(0)

#### Environment init
welcomeMessage = "I am preparing for reading, please wait a minute..."
welcomeMessagePixelWidth = normalFont.measure(welcomeMessage)
Label(rootWindow, text = welcomeMessage, font = normalFont, justify = LEFT, fg = foreGroundColor, bg = backGroundColor, anchor = N + W).place(relheight = 1, relwidth = 1, relx = (width - welcomeMessagePixelWidth) / 2 / width, rely = (height - fontSize) / 2 / height)
def closeWelcomeMessage():
    time.sleep(1)
    rootWindow.winfo_children()[0].destroy()
    turnPage(1)
_thread.start_new_thread(closeWelcomeMessage, ())

#### Events binds
from keybind import *
rootWindow.protocol('WM_DELETE_WINDOW', closeWithSaving)
mainloop()
